### ISSUE TITLE
VCF will not load in vcf.io.bio

### ISSUE THREAD

**Issue by chmille4** [iobio/planning#8]
Hi, I was trying to use your web app, but my VCF file does not seem to work.
 
The file is located here:
https://genome.med.nyu.edu/results/external/NYU/snuderllab/Sample1.vcf.gz
https://genome.med.nyu.edu/results/external/NYU/snuderllab/Sample1.vcf.gz.tbi
 
And here is the session I loaded with it:
http://vcf.iobio.io/?species=Human&build=GRCh37&vcf=https%3A%2F%2Fgenome.med.nyu.edu%2Fresults%2Fexternal%2FNYU%2Fsnuderllab%2FSample1.vcf.gz&tbi=https%3A%2F%2Fgenome.med.nyu.edu%2Fresults%2Fexternal%2FNYU%2Fsnuderllab%2FSample1.vcf.gz.tbi
 
Any ideas what could be wrong? The page just says 'Sampling' indefinitely. I checked the sample VCF's you had on the start page, and it looks like one of them was version 4.1 format, while mine is 4.2; maybe this is part of the issue?
 
Thanks
 
- Stephen

**Comment by tonydisera** [comment]
Hi Stephen -

I'm troubleshooting this right now.  Interestingly, when I download the file and load the local file into vcf.iobio, it works.  I will keep you posted.

Tony

**Comment by chmille4** [comment]
Hey tony, Stephen's not on this thread. He sent an email via iobioproject@gmail.com and I copied it here so that we can track it.  I can respond and let him know.

Do you get iobioproject@gmail.com emails?

**Comment by tonydisera** [comment]
I uploaded the vcf.gz and vcf.gz.tbi files to an S3 bucket, and it works fine.  

It must have something to do with tabix not being able to access the files served from the web server.  Here is the error I get when I run tabix from the command line:

/tabix -H https://genome.med.nyu.edu/results/external/NYU/snuderllab/Sample1.vcf.gz
[E::hts_open_format] fail to open file 'https://genome.med.nyu.edu/results/external/NYU/snuderllab/Sample1.vcf.gz'
Could not read https://genome.med.nyu.edu/results/external/NYU/snuderllab/Sample1.vcf.gz

I'll keep digging.

Tony

**Comment by chmille4** [comment]
Thanks tony, do you have the S3  link? I'll send the working link back to Stephen.

**Comment by tonydisera** [comment]
I just removed the files, but I can re-upload.  

It looks like there is a problem with the certificate on their server.  When I run curl, here is the error:

$ curl "https://genome.med.nyu.edu/results/external/NYU/snuderllab/Sample1.vcf.gz"
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

**Comment by chmille4** [comment]
Hmm, i don't see any curl problems. This works for me 
```curl https://genome.med.nyu.edu/results/external/NYU/snuderllab/Sample1.vcf.gz```

**Comment by chmille4** [comment]
but if I do `curl -I https://genome.med.nyu.edu/results/external/NYU/snuderllab/Sample1.vcf.gz` it gives a http status 301 on the header, which is resource permanently moved. I think there's some sort of redirect going on that tabix isn't supporting

**Comment by chmille4** [comment]
Was this resolved?

**Comment by tonydisera** [comment]
I haven't heard back from Stephen.  The local files now work with the wss fix, but there was still problems with the vcf served from https://genome.med.nyu.edu.  Do you want me to ping Stephen?

**Comment by chmille4** [comment]
No thats ok, I just followed up about the local install. I'll ask him then.
